### ISSUE TITLE
gobblin don't work in hadoop 2.7.1

### ISSUE THREAD

**Issue by zhaolmtravelsky** [linkedin/gobblin#321]
my hadoop env is hadoop 2.7.1. I compile gobblin with hadoop 2.7.1. My compile command is `cd gobblin && ./gradlew clean build -PuseHadoop2 -x test`. In build.gradle, I modify hadoopVersion=2.7.1.Howerver, gobblin don't work in hadoop 2.7.1. My run command is `sh  bin/gobblin-mapreduce.sh --jt localhost --fs localhost:8020 --workdir /home/data/test/gobbin_work --conf /home/data/test/gobblin/gobblin-dist/conf/kafka_hdfs.pull`. The stacktrace is below:

ERROR [AbstractJobLauncher] Failed to launch and run job job_PullFromKafka_1441588753512: java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.v2.util.MRApps.addLog4jSystemProperties(Ljava/lang/String;JILjava/util/List;)V
java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.v2.util.MRApps.addLog4jSystemProperties(Ljava/lang/String;JILjava/util/List;)V
	at org.apache.hadoop.mapred.YARNRunner.createApplicationSubmissionContext(YARNRunner.java:400)
	at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:284)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:240)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1287)
	at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:200)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:258)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:60)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by liyinan926** [comment]
@zhaolmtravelsky This issue sounds like the same as the previous issue #317 you have already resolved. Again, it looks like some Hadoop jar with the correct version 2.7.1 is not on the classpath.

**Comment by zhaolmtravelsky** [comment]
@liyinan926 

thank you ~~. you are right. my hadoop client is hadoop 2.3.1, but my hadoop cluster is hadoop 2.7.1. So the version is conflict. I use hadoop 2.7.1 client is right.
