### ISSUE TITLE
gobblin don't work in hadoop 2.7.1

### ISSUE THREAD

**Issue by zhaolmtravelsky** [linkedin/gobblin#317]
my hadoop env is hadoop 2.7.1, but it not work. The stacktrace is below:

ERROR [AbstractJobLauncher] Failed to launch and run job job_PullFromKafka_1441077867673: java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.v2.util.MRApps.crossPlatformifyMREnv(Lorg/apache/hadoop/conf/Configuration;Lorg/apache/hadoop/yarn/api/ApplicationConstants$Environment;)Ljava/lang/String;
java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.v2.util.MRApps.crossPlatformifyMREnv(Lorg/apache/hadoop/conf/Configuration;Lorg/apache/hadoop/yarn/api/ApplicationConstants$Environment;)Ljava/lang/String;
	at org.apache.hadoop.mapred.YARNRunner.createApplicationSubmissionContext(YARNRunner.java:390)
	at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:284)
	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282)
	at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:200)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:258)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:60)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

**Comment by chavdar** [comment]
Can you please describe what you did? Did you modify "hadoopVersion" in
build.gradle and recompile for 2.7.1?

**Comment by liyinan926** [comment]
@zhaolmtravelsky when you build gobblin, you can use the options `-PuseHadoop2 -PhadoopVersion=2.7.1` to compile gobblin against Hadoop 2.7.1.

**Comment by zhaolmtravelsky** [comment]
@chavdar  @liyinan926 

my compile command is `cd gobblin && ./gradlew clean build -PuseHadoop2 -x test`

I have modified `hadoopVersion = '2.7.1' ` in  `build.gradle `. 

The error stacktrace is above. So I doubt gobblin is suit for hadoop 2.7.1 ?

**Comment by liyinan926** [comment]
@zhaolmtravelsky the stack trace sounds to me like a wrong version of Hadoop jars on the classpath. Which command you used to run your Gobblin job?

**Comment by zhaolmtravelsky** [comment]
@liyinan926 

my run command is `sh  bin/gobblin-mapreduce.sh --jt  localhost --fs hdfs://localhost:8020  --workdir /home/data/test/gobbin_work --conf /home/data/test/gobblin/gobblin-dist/conf/kafka_hdfs.pull`. that command run in the gobblin parent directory. kafka_hdfs.pull is job configuration file.

**Comment by zhaolmtravelsky** [comment]
@liyinan926 @chavdar 

I have solved my probleam. The cause is that I compile gobblin with hadoop 2.7.1, but I didn't uncompress the new gobblin_dist tar package.

**Comment by chiyanram** [comment]
@zhaolmtravelsky @liyinan926  I am facing the same problem as above. i am using hadoop 2.7.1 version in maven also in gobblin-dist directory. still i am facing the same issue?
