### ISSUE TITLE
gobblin not working in hadoop 2.7.1

### ISSUE THREAD

**Issue by chiyanram** [linkedin/gobblin#1434]
2016-12-05 01:23:05 UTC ERROR [main] gobblin.runtime.AbstractJobLauncher  329 - Failed to launch and run job : java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.v2.util.MRApps.addLog4jSystemProperties(Lorg/apache/hadoop/mapred/Task;Ljava/util/List;Lorg/apache/hadoop/conf/Configuration;)V
java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.v2.util.MRApps.addLog4jSystemProperties(Lorg/apache/hadoop/mapred/Task;Ljava/util/List;Lorg/apache/hadoop/conf/Configuration;)V
        at org.apache.hadoop.mapred.YARNRunner.createApplicationSubmissionContext(YARNRunner.java:399)
        at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:285)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:536)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1296)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1293)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1293)
        at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:203)

I verified the issue https://github.com/linkedin/gobblin/issues/321...

We have hadoop 2.7.1 in classpath but still it's not working.

**Comment by chiyanram** [comment]
Command which i am using to run is 

{code}
/opt/gobblin-dist/bin/gobblin-mapreduce.sh start --conf /home/edpintdatd/jobs/gobblin/native.pull 
		--workdir /home/edpintdatd/jobs/gobblin/work
{code}
